### ISSUE TITLE
Please support php7

### ISSUE THREAD

**Issue by p-blomberg** [edruid/SnakeDruid#2]
When trying to require snakedruid via composer, this is what I get:
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for edruid/snake-druid ^0.1.9 -> satisfiable by edruid/snake-druid[v0.1.9].
>     - edruid/snake-druid v0.1.9 requires php ^5.6 -> your PHP version (7.0.3) does not satisfy that requirement.

**Comment by edruid** [comment]
I have updated the composer files in the branch `php7`, test suite passes in a manually created php7 environment but no such environment is automatically set up.
